### ISSUE TITLE
Table plugin enhancements

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/dicty-frontpage#155]
Putting all table plugin requests into one issue.

- [ ] Add table width / size #121 
- [ ] Change column width to make asymmetric table #124 
- [ ] Allow table lines to be white or invisible #129 

Something to consider: adding a new grid plugin that utilizes Material-UI's `Grid` component. This would allow for flexible and responsive layouts within the page. This would also help with #47, improving the behavior of images.
